# `view()` vs. `transpose()` vs. `reshape()`

In [1]:
import torch
import torch.nn as nn

In [73]:
t = torch.tensor([[[0, 1], [2,3], [4,5]], \
                 [[6,7], [8,9], [10,11]], \
                 [[12, 13], [14, 15], [16, 17]], \
                [[18, 19], [20, 21], [22, 23]]])

In [84]:
t.shape

torch.Size([4, 3, 2])

In [74]:
t

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]])

In [75]:
t[0][0][0]

tensor(0)

In [76]:
t[0][0][1]

tensor(1)

In [77]:
t[0][1][0]

tensor(2)

## view

In [78]:
tv = t.view(4, 2, 3)

In [79]:
tv

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])

In [81]:
tv[0][0][0]

tensor(0)

In [82]:
tv[0][0][1]

tensor(1)

In [83]:
tv[0][0][2]

tensor(2)

In [80]:
tv.is_contiguous()

True

In [68]:
t.flatten() == tv.flatten()

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True])

In [69]:
t.storage().data_ptr() == tv.storage().data_ptr()  # 물리적 pointer 값이 일치함

True

In [71]:
# Modifying view tensor changes base tensor as well.
t[0][0][0] = 99
tv[0][0][0]

tensor(99)

## transpose

In [85]:
tt = t.transpose(2, 1)  # (4, 2, 3)
tt

tensor([[[ 0,  2,  4],
         [ 1,  3,  5]],

        [[ 6,  8, 10],
         [ 7,  9, 11]],

        [[12, 14, 16],
         [13, 15, 17]],

        [[18, 20, 22],
         [19, 21, 23]]])

In [12]:
tt.shape == b.shape

True

In [13]:
t.storage().data_ptr() == tt.storage().data_ptr()

True

In [15]:
tt.is_contiguous()

False

In [86]:
tt.flatten()

tensor([ 0,  2,  4,  1,  3,  5,  6,  8, 10,  7,  9, 11, 12, 14, 16, 13, 15, 17,
        18, 20, 22, 19, 21, 23])

In [18]:
t.flatten() == tt.flatten()  # since tt is not contiguous 

tensor([ True,  True, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False,  True,  True])

## contiguous

In [87]:
tt.contiguous() == tt  # 겉보기에는 tt와 같음

tensor([[[True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True]],

        [[True, True, True],
         [True, True, True]]])

In [31]:
tt.contiguous().storage().data_ptr() == tt.storage().data_ptr()  #  하지만 물리적 pointer는 다름

False

## reshape

`== contiguous().view()`

In [92]:
tt.view(4, 3, 2)  # transpose -> view (x)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [90]:
tt.contiguous().view(4, 3, 2)  # transpose -> contiguous -> view (o)

tensor([[[ 0,  2],
         [ 4,  1],
         [ 3,  5]],

        [[ 6,  8],
         [10,  7],
         [ 9, 11]],

        [[12, 14],
         [16, 13],
         [15, 17]],

        [[18, 20],
         [22, 19],
         [21, 23]]])

In [91]:
tt.reshape(4, 3, 2)  # transpose -> reshape (o)

tensor([[[ 0,  2],
         [ 4,  1],
         [ 3,  5]],

        [[ 6,  8],
         [10,  7],
         [ 9, 11]],

        [[12, 14],
         [16, 13],
         [15, 17]],

        [[18, 20],
         [22, 19],
         [21, 23]]])

In [96]:
tt.reshape(4, 3, 2).is_contiguous()

True